import type { TTSVoice } from "./types";

export const VIENEU_PRESET_VOICES: TTSVoice[] = [
	{
		id: "Hải Đăng",
		name: "Hải Đăng",
		description: "Nam · Bắc · Phong cách tự nhiên",
		gender: "male",
		region: "Bắc",
		style: "Tự nhiên",
		featured: 1,
		aliases: ["Minh Quân Pro", "Minh Quân"],
	},
	{
		id: "Ngọc Huyền",
		name: "Ngọc Huyền",
		description: "Nữ · Bắc · Giọng đọc tự nhiên",
		gender: "female",
		region: "Bắc",
		style: "Tự nhiên",
		featured: 2,
	},
	{
		id: "Trúc Ly",
		name: "Trúc Ly",
		description: "Nữ · Bắc · Phong cách tự nhiên",
		gender: "female",
		region: "Bắc",
		style: "Tự nhiên",
		featured: 3,
	},
	{
		id: "Thiện Minh",
		name: "Thiện Minh",
		description: "Nam · Bắc · Phong cách kể chuyện",
		gender: "male",
		region: "Bắc",
		style: "Kể chuyện",
		featured: 4,
		aliases: ["Anh Khôi"],
	},
	{
		id: "Mai Anh",
		name: "Mai Anh",
		description: "Nữ · Bắc · Phong cách tin tức",
		gender: "female",
		region: "Bắc",
		style: "Tin tức",
		featured: 5,
	},
	{
		id: "Thùy Dung",
		name: "Thùy Dung",
		description: "Nữ · Nam · Phong cách tin tức",
		gender: "female",
		region: "Nam",
		style: "Tin tức",
		featured: 6,
	},
	{
		id: "Quang Sơn",
		name: "Quang Sơn",
		description: "Nam · Trung · Phong cách tự nhiên",
		gender: "male",
		region: "Trung",
		style: "Tự nhiên",
		featured: 7,
	},
	{
		id: "Ngọc Trân",
		name: "Ngọc Trân",
		description: "Nữ · Trung · Phong cách tự nhiên",
		gender: "female",
		region: "Trung",
		style: "Tự nhiên",
		featured: 8,
	},
	{
		id: "Adam bựa",
		name: "Adam bựa",
		description: "Nam · Bắc · Phong cách tự nhiên",
		gender: "male",
		region: "Bắc",
		style: "Tự nhiên",
		featured: 9,
	},
	{
		id: "Thiền Tâm Đức",
		name: "Thiền Tâm Đức",
		description: "Nam · Bắc · Phong cách kể chuyện",
		gender: "male",
		region: "Bắc",
		style: "Kể chuyện",
		featured: 10,
	},
	{
		id: "Minh Đức",
		name: "Minh Đức",
		description: "Nam · Bắc · Phong cách tin tức",
		gender: "male",
		region: "Bắc",
		style: "Tin tức",
	},
	{
		id: "Phạm Tuyên",
		name: "Phạm Tuyên",
		description: "Nam · Bắc · Phong cách tự nhiên",
		gender: "male",
		region: "Bắc",
		style: "Tự nhiên",
	},
	{
		id: "Thái Sơn",
		name: "Thái Sơn",
		description: "Nam · Nam · Phong cách kể chuyện",
		gender: "male",
		region: "Nam",
		style: "Kể chuyện",
	},
	{
		id: "Xuân Vĩnh",
		name: "Xuân Vĩnh",
		description: "Nam · Bắc · Phong cách tự nhiên",
		gender: "male",
		region: "Bắc",
		style: "Tự nhiên",
	},
	{
		id: "Thanh Bình",
		name: "Thanh Bình",
		description: "Nam · Bắc · Phong cách kể chuyện",
		gender: "male",
		region: "Bắc",
		style: "Kể chuyện",
	},
	{
		id: "Ngọc Linh",
		name: "Ngọc Linh",
		description: "Nữ · Bắc · Phong cách kể chuyện",
		gender: "female",
		region: "Bắc",
		style: "Kể chuyện",
	},
	{
		id: "Đoan Trang",
		name: "Đoan Trang",
		description: "Nữ · Bắc · Phong cách tự nhiên",
		gender: "female",
		region: "Bắc",
		style: "Tự nhiên",
	},
	{
		id: "Thục Đoan",
		name: "Thục Đoan",
		description: "Nữ · Nam · Phong cách kể chuyện",
		gender: "female",
		region: "Nam",
		style: "Kể chuyện",
	},
	{
		id: "Minh Triết",
		name: "Minh Triết",
		description: "Nam · Nam · Phong cách tin tức",
		gender: "male",
		region: "Nam",
		style: "Tin tức",
	},
	{
		id: "Mỹ Duyên",
		name: "Mỹ Duyên",
		description: "Nữ · Nam · Phong cách đọc truyện",
		gender: "female",
		region: "Nam",
		style: "Kể chuyện",
	},
	{
		id: "Quỳnh Anh",
		name: "Quỳnh Anh",
		description: "Nữ · Bắc · Phong cách đọc truyện",
		gender: "female",
		region: "Bắc",
		style: "Kể chuyện",
	},
	{
		id: "Đức Trí",
		name: "Đức Trí",
		description: "Nam · Nam · Phong cách đọc truyện",
		gender: "male",
		region: "Nam",
		style: "Kể chuyện",
	},
	{
		id: "Kim Thanh",
		name: "Kim Thanh",
		description: "Nữ · Nam · Phong cách đọc truyện",
		gender: "female",
		region: "Nam",
		style: "Kể chuyện",
	},
	{
		id: "Adam",
		name: "Adam",
		description: "Nam · Nam · Giọng đọc tự nhiên",
		gender: "male",
		region: "Nam",
		style: "Tự nhiên",
	},
	{
		id: "Quốc Tuấn",
		name: "Quốc Tuấn",
		description: "Nam · Bắc · Phong cách tự nhiên",
		gender: "male",
		region: "Bắc",
		style: "Tự nhiên",
	},
];

export const KNOWN_VOICE_SET = new Set(VIENEU_PRESET_VOICES.map((v) => v.id));

// Map Edge TTS voice IDs and aliases to VieNeu preset voices.
export const VOICE_MAP: Record<string, string> = {
	"vi-VN-HoaiMyNeural": "Ngọc Huyền",
	"vi-VN-NamMinhNeural": "Hải Đăng",
	"Minh Quân Pro": "Hải Đăng",
	"Minh Quân": "Hải Đăng",
	"Anh Khôi": "Thiện Minh",
};

export function resolveVieNeuVoice(voiceName?: string): string {
	if (!voiceName) return "Hải Đăng";
	if (VOICE_MAP[voiceName]) return VOICE_MAP[voiceName];
	if (KNOWN_VOICE_SET.has(voiceName)) return voiceName;
	return "Hải Đăng";
}
